version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: db_app
    expose:
      - 5432
    env_file:
      - .env-non-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_app
    ports:
      - 4000:6379
    expose:
      - 6379

  fastapi:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: >
      sh -c "
      alembic upgrade head &&
      gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:5002
      "
    ports:
      - 5002:5002
    expose:
      - 5002
    depends_on:
      - db
      - redis

  react:
    build:
      context: ./reactjs
      dockerfile: ./Dockerfile
    container_name: react_app
    ports:
      - 5001:5001
    expose:
      - 5001
    depends_on:
      - fastapi

volumes:
  postgres_data: