version: "3.8"
services:
  db:
    image: postgres:16
    container_name: db_app
    expose:
      - 5432
    env_file:
      - .env-non-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_app
    ports:
      - 4343:6379
    expose:
      - 6379

  fastapi:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: >
      sh -c "wait-for-it db:5432 -- alembic upgrade head && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
      - redis

  react:
    build:
      context: ./reactjs
      dockerfile: ./Dockerfile
    container_name: react_app
    ports:
      - 5173:5173
    expose:
      - 5173
    depends_on:
      - fastapi

volumes:
  postgres_data: